const AMOUNT_OF_DESTROYERS = 4;
const MIN_INPUT_LENGTH = 2;
const NEW_GAME_AGREEMENT_COMPLETE_LENGTH = 2;
const BOTH_FLEETS_READY_COMPLETE_LENGTH = 2;
const TIME_DIVIDER = 60;
const APPEAR_TIME = 100;

export {
  AMOUNT_OF_DESTROYERS,
  MIN_INPUT_LENGTH,
  NEW_GAME_AGREEMENT_COMPLETE_LENGTH,
  BOTH_FLEETS_READY_COMPLETE_LENGTH,
  TIME_DIVIDER,
  APPEAR_TIME,
};
