const AMOUNT_OF_DESTROYERS = 4;
const MIN_INPUT_LENGTH = 2;
const NEW_GAME_AGREEMENT_COMPLETE_LENGTH = 2;
const BOTH_FLEETS_READY_COMPLETE_LENGTH = 2;
const IN_BETWEEN_SHIP_PART_LENGTH = 4;
const TIME_DIVIDER = 60;
const APPEAR_TIME = 100;
const TIME_LENGTHS = {
  shotTime: 30,
  bonusTime: 10,
};

export {
  AMOUNT_OF_DESTROYERS,
  MIN_INPUT_LENGTH,
  NEW_GAME_AGREEMENT_COMPLETE_LENGTH,
  BOTH_FLEETS_READY_COMPLETE_LENGTH,
  IN_BETWEEN_SHIP_PART_LENGTH,
  TIME_DIVIDER,
  APPEAR_TIME,
  TIME_LENGTHS,
};
